version:                     '2.1'
services:
  proxy:
    build:                   proxy
    ports:
      - "6000:80"
    networks:
      app_net:

  proxy-internal:
    build:                   proxy-internal
  networks:
    app_net:

  mariadb:
    image:                   mariadb:10.5.2
    environment:
      MYSQL_ROOT_PASSWORD:   JacPV7QZ
      MYSQL_DATABASE:        monstercatDB
      MYSQL_DATABASE:        monstercatUser
      MYSQL_PASSWORD:        j4b58mYq
      MYSQL_ROOT_HOST:       "%"
    restart:                 always
    volumes:
     - ${PWD}/mariadb:/var/lib/mysql
    networks:
      app_net:

  web:
    build:                   javascript
    command:                 node api/api.js
    working_dir:             /app/
    restart:                 always
    volumes:
      - static-content:/app
    networks:
      app_net:

  database-catalog:
    build:                   javascript
    command:                 node api/database/host/database-catalog.js
    working_dir:             /app/
    restart:                 always
    volumes:
      - static-content:/app
    networks:
      app_net:

  database-releases:
    build:                   javascript
    command:                 node api/database/host/database-releases.js
    working_dir:             /app/
    restart:                 always
    volumes:
      - static-content:/app
    networks:
      app_net:

  database-artists:
    build:                   javascript
    command:                 node api/database/host/database-artists.js
    working_dir:             /app/
    restart:                 always
    volumes:
      - static-content:/app
    networks:
      app_net:

  database-session:
    build:                   javascript
    command:                 node api/database/host/database-session.js
    working_dir:             /app/
    restart:                 always
    volumes:
      - static-content:/app
    networks:
      app_net:

  database-local:
    build:                   javascript
    command:                 node api/database/local/database-local.js
    working_dir:             /app/
    restart:                 always
    volumes:
      - static-content:/app
    networks:
      app_net:

  database-update-catalog:
    build:                   javascript
    command:                 node api/database/update/database-update-catalog.js
    working_dir:             /app/
    restart:                 always
    volumes:
      - static-content:/app
    networks:
      app_net:

  database-update-releases:
    build:                   javascript
    command:                 node api/database/update/database-update-releases.js
    working_dir:             /app/
    restart:                 always
    volumes:
      - static-content:/app
    networks:
      app_net:

  database-update-artists:
    build:                   javascript
    command:                 node api/database/update/database-update-artists.js
    working_dir:             /app/
    restart:                 always
    volumes:
      - static-content:/app
    networks:
      app_net:

  recg:
    build:                   javascript
    command:                 node image/image-recognition.js
    working_dir:             /app/
    restart:                 always
    volumes:
      - static-content:/app
    networks:
      app_net:

volumes:
  static-content:
    driver_opts:
      type:                  tmpfs
      device:                tmpfs

networks:
  app_net:
    enable_ipv6:             true
    driver:                  bridge
    ipam:
      driver:                default
      config:
        - subnet:            2001:3200:3200::/64
          gateway:           2001:3200:3200::1
