version:                     '3'
services:
  proxy:
    build:                   proxy
    ports:
      - "6000:80"
    volumes:
      - ${PWD}/static-content:/app/static
    restart:                 always

  proxy-internal:
    build:                   proxy-internal
    restart:                 always

  mariadb:
    image:                   mariadb:10.5.2
    environment:
      MYSQL_ROOT_PASSWORD:   JacPV7QZ
      MYSQL_DATABASE:        monstercatDB
      MYSQL_DATABASE:        monstercatUser
      MYSQL_PASSWORD:        j4b58mYq
      MYSQL_ROOT_HOST:       "%"
    restart:                 always
    volumes:
     - ${PWD}/mariadb:/var/lib/mysql

  web:
    build:                   javascript
    command:                 node api/api.js
    working_dir:             /app/
    restart:                 always
    volumes:
      - ${PWD}/static-content:/app/static
      - ${PWD}/javascript/utils.js:/app/utils.js
      - ${PWD}/javascript/sqlhelper.js:/app/sqlhelper.js

  cover-image:
    build:                   javascript
    command:                 node api/cover-image.js
    working_dir:             /app/
    restart:                 always
    volumes:
      - ${PWD}/static-content:/app/api/static
      - ${PWD}/javascript/utils.js:/app/utils.js
      - ${PWD}/javascript/sqlhelper.js:/app/sqlhelper.js

  related-api:
    build:                   javascript
    command:                 node api/related.js
    working_dir:             /app/
    restart:                 always
    volumes:
      - ${PWD}/static-content:/app/static
      - ${PWD}/javascript/utils.js:/app/utils.js
      - ${PWD}/javascript/sqlhelper.js:/app/sqlhelper.js

  database-logs:
    build:                   javascript
    command:                 node database/host/database-logs.js
    working_dir:             /app/
    restart:                 always
    volumes:
      - ${PWD}/javascript/utils.js:/app/utils.js
      - ${PWD}/javascript/sqlhelper.js:/app/sqlhelper.js

  database-catalog-release:
    build:                   javascript
    command:                 node database/host/database-catalog-release.js
    working_dir:             /app/
    restart:                 always
    volumes:
      - ${PWD}/javascript/utils.js:/app/utils.js
      - ${PWD}/javascript/sqlhelper.js:/app/sqlhelper.js

  database-catalog:
    build:                   javascript
    command:                 node database/host/database-catalog.js
    working_dir:             /app/
    restart:                 always
    volumes:
      - ${PWD}/javascript/utils.js:/app/utils.js
      - ${PWD}/javascript/sqlhelper.js:/app/sqlhelper.js

  database-releases:
    build:                   javascript
    command:                 node database/host/database-releases.js
    working_dir:             /app/
    restart:                 always
    volumes:
      - ${PWD}/javascript/utils.js:/app/utils.js
      - ${PWD}/javascript/sqlhelper.js:/app/sqlhelper.js

  database-artists:
    build:                   javascript
    command:                 node database/host/database-artists.js
    working_dir:             /app/
    restart:                 always
    volumes:
      - ${PWD}/javascript/utils.js:/app/utils.js
      - ${PWD}/javascript/sqlhelper.js:/app/sqlhelper.js

  database-session:
    build:                   javascript
    command:                 node database/host/database-session.js
    working_dir:             /app/
    restart:                 always
    volumes:
      - ${PWD}/javascript/utils.js:/app/utils.js
      - ${PWD}/javascript/sqlhelper.js:/app/sqlhelper.js

  database-update-catalog:
    build:                   javascript
    command:                 node database/update/database-update-catalog.js
    working_dir:             /app/
    restart:                 always
    volumes:
      - ${PWD}/static-content:/app/static
      - ${PWD}/javascript/utils.js:/app/utils.js
      - ${PWD}/javascript/sqlhelper.js:/app/sqlhelper.js

  database-update-releases:
    build:                   javascript
    command:                 node database/update/database-update-releases.js
    working_dir:             /app/
    restart:                 always
    volumes:
      - ${PWD}/javascript/utils.js:/app/utils.js
      - ${PWD}/javascript/sqlhelper.js:/app/sqlhelper.js

  database-update-artists:
    build:                   javascript
    command:                 node database/update/database-update-artists.js
    working_dir:             /app/
    restart:                 always
    volumes:
      - ${PWD}/javascript/utils.js:/app/utils.js
      - ${PWD}/javascript/sqlhelper.js:/app/sqlhelper.js
