version:                     '3'
services:
  proxy:
    build:                   proxy
    ports:
      - "6000:80"

  proxy-internal:
    build:                   proxy-internal

  mariadb:
    image:                   mariadb:10.5.2
    environment:
      MYSQL_ROOT_PASSWORD:   JacPV7QZ
      MYSQL_DATABASE:        monstercatDB
      MYSQL_DATABASE:        monstercatUser
      MYSQL_PASSWORD:        j4b58mYq
      MYSQL_ROOT_HOST:       "%"
    restart:                 always
    volumes:
     - ${PWD}/mariadb:/var/lib/mysql

  web:
    build:                   javascript
    command:                 node api/api.js
    working_dir:             /app/
    restart:                 always
    volumes:
      - static-content:/app
    deploy:
      replicas:              5

  database-catalog:
    build:                   javascript
    command:                 node api/database/host/database-catalog.js
    working_dir:             /app/
    restart:                 always
    volumes:
      - static-content:/app
    deploy:
      replicas:              5

  database-releases:
    build:                   javascript
    command:                 node api/database/host/database-releases.js
    working_dir:             /app/
    restart:                 always
    volumes:
      - static-content:/app
    deploy:
      replicas:              5

  database-artists:
    build:                   javascript
    command:                 node api/database/host/database-artists.js
    working_dir:             /app/
    restart:                 always
    volumes:
      - static-content:/app
    deploy:
      replicas:              5

  database-session:
    build:                   javascript
    command:                 node api/database/host/database-session.js
    working_dir:             /app/
    restart:                 always
    volumes:
      - static-content:/app
    deploy:
      replicas:              5

  database-local:
    build:                   javascript
    command:                 node api/database/local/database-local.js
    working_dir:             /app/
    restart:                 always
    volumes:
      - static-content:/app

  database-update-catalog:
    build:                   javascript
    command:                 node api/database/update/database-update-catalog.js
    working_dir:             /app/
    restart:                 always
    volumes:
      - static-content:/app

  database-update-releases:
    build:                   javascript
    command:                 node api/database/update/database-update-releases.js
    working_dir:             /app/
    restart:                 always
    volumes:
      - static-content:/app

  database-update-artists:
    build:                   javascript
    command:                 node api/database/update/database-update-artists.js
    working_dir:             /app/
    restart:                 always
    volumes:
      - static-content:/app

  recg:
    build:                   javascript
    command:                 node image/image-recognition.js
    working_dir:             /app/
    restart:                 always
    volumes:
      - static-content:/app
    environment:
      ENABLE_IPV6:           true

volumes:
  static-content:
    driver_opts:
      type:                  tmpfs
      device:                tmpfs
