version: '1'
services:
  web:
    build: .
    command: 'bash -c scripts/run-api.sh'
    environment:
      PORT: 5000  
    ports:
      - "5000:5000"
  recg:
    build: .
    command: 'bash -c bash scripts/run-recg.sh'
