version:                     '3'
services:
  proxy:
    build:                   proxy
    ports:
      - "6000:80"
    volumes:
      - ${PWD}/static-content:/app/static
    restart:                 always

  proxy-internal:
    build:                   proxy-internal
    restart:                 always

  mariadb:
    image:                   mariadb:10.5.2
    environment:
      MYSQL_ROOT_PASSWORD:   JacPV7QZ
      MYSQL_DATABASE:        monstercatDB
      MYSQL_DATABASE:        monstercatUser
      MYSQL_PASSWORD:        j4b58mYq
      MYSQL_ROOT_HOST:       "%"
    restart:                 always
    volumes:
     - ${PWD}/mariadb:/var/lib/mysql

  web:
    build:                   javascript/api
    command:                 node api/api.js
    working_dir:             /app/
    restart:                 always
    volumes:
      - ${PWD}/static-content:/app/static
      - ${PWD}/private-static-content:/app/static-private
      - ${PWD}/javascript/apiclient:/app/apiclient
      - ${PWD}/server_config.json:/app/server_config.json

  release-api:
    build:                   javascript/api
    command:                 node api/release-api.js
    working_dir:             /app/
    restart:                 always
    volumes:
      - ${PWD}/static-content:/app/api/static

  related-api:
    build:                   javascript/api
    command:                 node api/related-api.js
    working_dir:             /app/
    restart:                 always

  database-logs:
    build:                   javascript/api
    command:                 node database/host/database-logs.js
    working_dir:             /app/
    restart:                 always

  database-catalog-release:
    build:                   javascript/api
    command:                 node database/host/database-catalog-release.js
    working_dir:             /app/
    restart:                 always

  database-catalog:
    build:                   javascript/api
    command:                 node database/host/database-catalog.js
    working_dir:             /app/
    restart:                 always

  database-releases:
    build:                   javascript/api
    command:                 node database/host/database-releases.js
    working_dir:             /app/
    restart:                 always

  database-artists:
    build:                   javascript/api
    command:                 node database/host/database-artists.js
    working_dir:             /app/
    restart:                 always

  database-session:
    build:                   javascript/api
    command:                 node database/host/database-session.js
    working_dir:             /app/
    restart:                 always

  database-local:
    build:                   javascript/api
    command:                 node database/local/database-local.js
    working_dir:             /app/
    restart:                 always

  database-update-catalog:
    build:                   javascript/api
    command:                 node database/update/database-update-catalog.js
    working_dir:             /app/
    restart:                 always

  database-update-releases:
    build:                   javascript/api
    command:                 node database/update/database-update-releases.js
    working_dir:             /app/
    restart:                 always

  database-update-artists:
    build:                   javascript/api
    command:                 node database/update/database-update-artists.js
    working_dir:             /app/
    restart:                 always

  webui:
    build:                   javascript/webui
    command:                 npm start
    working_dir:             /app/webui
    restart:                 always

  database-authentication:
    build:                   javascript/api
    command:                 node database/database-authentication.js
    working_dir:             /app/
    restart:                 always
