version:                     '3'
services:
  database-catalog:
    build:                   .
    command:                 node javascript/database/host/database-catalog.js
    working_dir:             /app/
    restart:                 always
    volumes:
      - static-content:/app

  database-releases:
    build:                   .
    command:                 node javascript/database/host/database-releases.js
    working_dir:             /app/
    restart:                 always
    volumes:
      - static-content:/app

  database-artists:
    build:                   .
    command:                 node javascript/database/host/database-artists.js
    working_dir:             /app/
    restart:                 always
    volumes:
      - static-content:/app

  database-local:
    build:                   .
    command:                 node javascript/database/local/database-local.js
    working_dir:             /app/
    restart:                 always
    volumes:
      - static-content:/app

  database-update-catalog:
    build:                   .
    command:                 node javascript/database/update/database-update-catalog.js
    working_dir:             /app/
    restart:                 always
    volumes:
      - static-content:/app

  database-update-releases:
    build:                   .
    command:                 node javascript/database/update/database-update-releases.js
    working_dir:             /app/
    restart:                 always
    volumes:
      - static-content:/app

  database-update-artists:
    build:                   .
    command:                 node javascript/database/update/database-update-artists.js
    working_dir:             /app/
    restart:                 always
    volumes:
      - static-content:/app

  web:
    build:                   .
    command:                 node javascript/api/api.js
    working_dir:             /app/
    restart:                 always
    volumes:
      - static-content:/app
  recg:
    build:                   .
    command:                 node javascript/image/image-recognition.js
    working_dir:             /app/
    restart:                 always
    volumes:
      - static-content:/app

  proxy:
    build:                   proxy
    ports:
      - "6000:80"

volumes:
  static-content:
