version: '3'
services:
  web:
    build: .
    command: node javascript/index.js
    environment:
      PORT: 5000
    ports:
      - "5000:5000"
    working_dir: /app/
    volumes:
      - static-content:/app
  recg:
    build: .
    command: node javascript/recognitiontask.js
    working_dir: /app/
    volumes:
      - static-content:/app

volumes:
  static-content:
