version: '3'
services:
  web:
    build: .
    command: node javascript/index.js
    environment:
      PORT: 5000
    ports:
      - "5000:5000"
    volumes:
      - './app/'
  recg:
    build: .
    command: node javascript/recognitiontask.js
    volumes:
      - './app/'
