version: '3'
services:
  database:
    build: .
    command: node javascript/database.js
    environment:
      PORT: 6000
    ports:
      - "6000:6000"
    working_dir: /app/
    restart: always
    volumes:
      - static-content:/app

  web:
    build: .
    command: node javascript/api.js
    environment:
      PORT: 5000
    ports:
      - "5000:5000"
    working_dir: /app/
    restart: always
    volumes:
      - static-content:/app
  recg:
    build: .
    command: node javascript/image-recognition.js
    working_dir: /app/
    restart: always
    volumes:
      - static-content:/app

volumes:
  static-content:
